iphpsand_photo:
    resource: "@IphpsandPhotoBundle/Resources/config/routing.yml"
    prefix:   /

app_first:
    resource: "@AppFirstBundle/Resources/config/routing.yml"
    prefix:   /
iphpsand_photo:
    pattern:  /photo/
    defaults: { _controller: IphpsandPhotoBundle:Photo:index }
