App\FirstBundle\Entity\AllCommand:
    type: entity
    table: null
    repositoryClass: App\FirstBundle\Entity\CommandRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nametim:
            type: string
            length: 255
        club:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
            nametim:
                targetEntity: Command
                mappedBy: name
