App\FirstBundle\Entity\Command:
    type: entity
    repositoryClass: App\FirstBundle\Entity\TimRepository
    table: tim
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        trainer:
            type: string
            length: 100
        stadium:
            type: string
            length: 100
        captain:
            type: string
            length: 100
    manyToOne:
            name:
                targetEntity: AllCommand
                inversedBy: nametim
                joinColumn:
                    name: name
                    referencedColumnName: id