App\FirstBundle\Entity\Tims:
    type: entity
    table: tims
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
