<?php

namespace App\FirstBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimRepository extends EntityRepository
{
}
